# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
  pull_request:
    branches: [ "master" ]

jobs:
  build-apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build apks
        run: |
          flutter pub get
          flutter build apk --release --tree-shake-icons
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --release --tree-shake-icons
          mkdir -p releases
          mv -f build/app/outputs/flutter-apk/*-release.apk releases
          mv -f releases/app-release.apk releases/app-universal-release.apk
      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "releases/*-release.apk"
          token: ${{ secrets.WF_ACTION_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        
      - name: build
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install zip
          zip -r ios-release.ipa Payload
      - name: Release iOS
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.WF_ACTION_TOKEN }}
          artifacts: "ios-release.ipa"
          tag: ${{ github.event.inputs.TAG }}
